import { Tarefa } from '@/types/tarefa'
const taskLimitNumber = 10

export const columnsRawData = [
  {
    id: 1,
    name: 'Domingo',
    limit: taskLimitNumber,
    tasks: [
      {
        id_tarefa: 1,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
      {
        id_tarefa: 2,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
    ] as Tarefa[],
  },
  {
    id: 2,
    name: 'Segunda',
    limit: taskLimitNumber,
    tasks: [
      {
        id_tarefa: 1,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
      {
        id_tarefa: 2,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
    ] as Tarefa[],
  },
  {
    id: 3,
    name: 'Terça',
    limit: taskLimitNumber,
    tasks: [
      {
        id_tarefa: 1,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
      {
        id_tarefa: 2,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
    ] as Tarefa[],
  },
  {
    id: 4,
    name: 'Quarta',
    limit: taskLimitNumber,
    tasks: [
      {
        id_tarefa: 1,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
      {
        id_tarefa: 2,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
    ] as Tarefa[],
  },
  {
    id: 5,
    name: 'Quinta',
    limit: taskLimitNumber,
    tasks: [] as Tarefa[],
  },
  {
    id: 6,
    name: 'Sexta',
    limit: taskLimitNumber,
    tasks: [
      {
        id_tarefa: 1,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
      {
        id_tarefa: 2,
        nome_tarefa: 'bla',
        descricao: 'blabla',
        dt_inicial: new Date(),
        dt_final: new Date(),
        hora: 20,
        id_usuario: 1,
        stts_tarefa: false,
      },
    ] as Tarefa[],
  },
  {
    id: 7,
    name: 'Sábado',
    limit: taskLimitNumber,
    tasks: [],
  },
]
